apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
spec:
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox
    #this does not work in my environment
    #- wget
    #- "-O"
    #- "/work-dir/index.html"
    #- http://kubernetes.io
    command: ["/bin/sh","-c","echo ok!! >> /work-dir/index.html"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {} 
