apiVersion: v1
kind: Pod
metadata:
  name: busybox-vn-left-1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "vn-left-1" }
    ]'
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    stdin: true
    tty: true
  restartPolicy: Always

