apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-csrx
  labels:
    app: csrx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csrx
  template:
    metadata:
      labels:
        app: csrx
      annotations:
       k8s.v1.cni.cncf.io/networks: '[
           { "name": "vn-left-1" },
           { "name": "vn-right-1" }
       ]'
    spec:
      containers:
      - name: csrx
        image: csrx
        volumeMounts:
        - name: wrapper
          mountPath: /scripts
        ports:
        - containerPort: 22
        imagePullPolicy: Never
        stdin: true
        tty: true
        env:
        - name: CSRX_ROOT_PASSWORD 
          value: "contrail123"
        securityContext:
          privileged: true
      volumes:
      - name: wrapper
        configMap:
          name: wrapper
          defaultMode: 0744
