apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-vn-left-2
  labels:
    app: ubuntuapp
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        { "name": "vn-left-1" }
    ]'
spec:
  containers:
    - name: ubuntuapp
      image: virtualhops/ato-ubuntu:latest
      securityContext:
          privileged: true

